-- AlterTable
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "teacherUserId" VARCHAR(36);
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "plan" VARCHAR(20) NOT NULL DEFAULT 'free';
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "compileCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "rcCustomerId" VARCHAR(80);
