-- AlterTable
ALTER TABLE "Page" ADD COLUMN "handText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Page" ADD COLUMN "diagram" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Page" ADD COLUMN "diagramUrl" VARCHAR(2000);
